#!/usr/bin/env sh

DOTFILES_DIR=$(cd $(dirname "$0")/.. && pwd)

if [ $CODESPACES ]; then

  # Always want to use ZSH as my default shell (e.g. for SSH)
  if ! grep -q "root.*/bin/zsh" /etc/passwd
  then
    apt-get install -y zsh
    chsh -s /bin/zsh root
  fi

  # Install GitHub CLI
  curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | dd of=/etc/apt/trusted.gpg.d/githubcli-archive-keyring.gpg
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/trusted.gpg.d/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null
  apt update
  apt install gh

  # Install other utilities
  apt-get install -y \
    ripgrep
fi

export ZSH=$HOME/.oh-my-zsh
if [ ! -d "$ZSH" ]; then
  echo "Installing oh-my-zsh..."
  git clone https://github.com/ohmyzsh/ohmyzsh.git $ZSH
else
  echo "Updating oh-my-zsh..."
  cd $ZSH
  git pull
fi

if [ ! -d $ZSH/custom/plugins/zsh-autosuggestions ]; then
  echo "Installing zsh-autosuggestions..."
  git clone https://github.com/zsh-users/zsh-autosuggestions.git $ZSH/plugins/zsh-autosuggestions
else
  echo "Updating zsh-autosuggestions..."
  cd $ZSH/plugins/zsh-autosuggestions
  git pull
fi

if [ ! -d $ZSH/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting ]; then
  echo "Installing zsh-syntax-highlighting..."
  git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $ZSH/plugins/zsh-syntax-highlighting
else
  echo "Updating zsh-syntax-highlighting..."
  cd $ZSH/plugins/zsh-syntax-highlighting
  git pull
fi

echo "Creating symlinks..."
ln -s ${DOTFILES_DIR}/zshrc ~/.zshrc
ln -s ${DOTFILES_DIR}/gitconfig ~/.gitconfig

echo "Finished installing dotfiles"
